feat: include codes
eduardabenevenutti77/website-explicativo pull request #14
Opened 2024-08-31 20:30 UTC by eduardabenevenutti77

2024-08-31 23:20 UTC, carolainesantos approved these changes, later dismissed

2024-09-01 13:07 UTC, carolainesantos requested changes

2024-09-01 13:07 UTC, carolainesantos commented on html-page.html
> -      <p class="sub-title">Exemplo 1 (html):</p>
Não entendi pq removeu essa parte!

2024-09-01 13:07 UTC, carolainesantos commented on html-page.html
> -      <img id="img-estrutura-html" src="./imgs/html-page/estrutura-html.png" alt="estrutura-HTML">
Essa parte já foi corrigida em outro pr favor não mexer !

2024-09-01 13:07 UTC, carolainesantos commented on html-page.html
> -      <p class="sub-title">Exemplo 2 (head):</p>
Favor não alterar !!

2024-09-01 13:07 UTC, carolainesantos commented on js-page.html
> -    <section id="javascript" class="sections">
Isso era pra ser removido?? 
Favor analisar, pois esse conteúdo é de outra pessoa.

2024-09-01 13:23 UTC, eduardabenevenutti77 commented on html-page.html
> -      <img id="img-estrutura-html" src="./imgs/html-page/estrutura-html.png" alt="estrutura-HTML">
alterei somente nas partes que estavam dando conflito, retirando os caracteres (=========) que aparecem.........

2024-09-01 13:24 UTC, closed without merging